name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  jobs_buildenv:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: hack/build_info.sh install_apt
      - run: aarch64-linux-gnu-gcc --version
      - run: make config
      - run: make build
